name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'Digger specification for the workflow'
        required: true
      run_name:
        description: 'Optional run name for the workflow'
        required: false

run-name: '${{inputs.run_name}}'

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 # Don't upgrade to v6 until this issue is resolved: https://github.com/diggerhq/digger/issues/2468

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ vars.INFRACOST_API_KEY }} # TODO: Change to secrets.INFRACOST_API_KEY

      - name: ${{ fromJSON(github.event.inputs.spec).job_id }}
        run: echo "job id ${{ fromJSON(github.event.inputs.spec).job_id }}"
        if: github.event.inputs.spec != ''

      - name: Run Digger
        uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ inputs.spec }}
          setup-terraform: true
          terraform-version: '1.14.2'
          setup-checkov: true
          checkov-version: '3.2.495'
          setup-aws: true
          aws-role-to-assume: ${{ vars.AWS_ROLE_ARN }} # TODO: Change to secrets.AWS_ROLE_ARN
          aws-region: ${{ vars.AWS_REGION }}
          # upload-plan-destination: 'aws'   # Since the plans bucket is S3
          # upload-plan-destination-s3-bucket: '{NAME_OF_YOUR_PLAN_BUCKET}'
          reporting-strategy: multiple_comments

        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional if you're using remote modules from your own private repo
          # GIT_CONFIG_COUNT: "1"
          # GIT_CONFIG_KEY_0: "url.https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf"
          # GIT_CONFIG_VALUE_0: "ssh://git@github.com/"
